### ISSUE TITLE
Make `local` logging driver default for new projects

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#57]
As per #56 , the `local` logging driver should be made default. This will be configurable in future, however, so the logging driver mechanism should be extensible and configurable.

## Preliminary Design Ideas
- Create new folder `assets/src/docker_logging` with templated.
- Add variables in `variables.tf` and `terraform.tfvars` to control templated values.
- Update Ansible to install rendered template file to /etc/docker/daemon.json` and restart docker daemon.

**Comment by gwright99** [comment]
Working.

![image](https://github.com/seqeralabs/cx-field-tools-installer/assets/1309341/1c9eaff2-f06b-4ad7-8ac6-514e2be22e46)

**Comment by adriannavarrobetrian** [comment]
I tried 

`flag_docker_logging_local              = false
flag_docker_logging_journald           = true
flag_docker_logging_jsonfile           = false`
`

and it works.

But when trying to change to a different one and apply again I get the following error.
╷
│ Error: local-exec provisioner error
│ 
│   with null_resource.copy_files_to_vm[0],
│   on 011_configure_vm.tf line 10, in resource "null_resource" "copy_files_to_vm":
│   10:   provisioner "local-exec" {
│ 
│ Error running command '
│ set -e
│ 
│ # SSH on host can be slow to initially respond. Attempt connection for 1 minute.
│ counter=0
│ until ssh tower-dev || [ $counter -gt 60 ]; do
│   echo "Waiting for SSH connection to be available."
│   sleep 5
│   counter=$((counter+5))
│ done
│ 
│ # On remote VM, purge old target folder & transfer new target folder
│ ssh tower-dev 'cd /home/ec2-user && rm -rf target || true'
│ scp -r assets/target tower-dev:/home/ec2-user/target
│ 
│ # Once new target folder copied, replace all remaining Tower-related files.
│ ssh tower-dev '/bin/bash /home/ec2-user/target/bash/remote/cleanse_and_configure_host.sh'
│ 
│ echo "Waiting for Ansible to be ready"
│ ssh tower-dev 'cd /home/ec2-user/target/ansible && chmod u+x 00_wait_for_ansible.sh && ./00_wait_for_ansible.sh'
│ 
│ echo "Loading System Packages"
│ ssh tower-dev 'set -e && cd /home/ec2-user/target/ansible && ansible-playbook 01_load_system_packages.yml'
│ 
│ echo "Updating Configuration Files"
│ ssh tower-dev 'cd /home/ec2-user/target/ansible && ansible-playbook 02_update_file_configurations.yml'
│ 
│ echo "Pulling containers and running Tower"
│ ssh tower-dev 'cd /home/ec2-user/target/ansible && ansible-playbook 03_pull_containers_and_run_tower.yml'
│ 
│ echo "Wait for Tower containers to be ready"
│ ssh tower-dev 'cd /home/ec2-user/target/ansible && ansible-playbook 04_wait_for_tower.yml'
│ 
│ echo "Patching Groundswell (if necessary)"
│ ssh tower-dev 'cd /home/ec2-user/target/ansible && ansible-playbook 05_patch_groundswell.yml'
│ 
│ ': exit status 2. Output: Pseudo-terminal will not be allocated because stdin is not a terminal.
│    ,     #_
│    ~\_  ####_
│   ~~  \_#####\
│   ~~     \###|
│   ~~       \#/ ___   Amazon Linux 2023 (ECS Optimized)
│    ~~       V~' '->
│     ~~~         /
│       ~~._.   _/
│          _/ _/
│        _/m/'
│ 
│ For documentation, visit http://aws.amazon.com/documentation/ecs
│ Waiting for Ansible to be ready
│ Loading System Packages
│ [WARNING]: No inventory was parsed, only implicit localhost is available
│ [WARNING]: provided hosts list is empty, only localhost is available. Note that
│ the implicit localhost does not match 'all'
│ 
│ PLAY [localhost] ***************************************************************
│ 
│ TASK [Gathering Facts] *********************************************************
│ ok: [localhost]
│ 
│ TASK [Install wget & nano.] ****************************************************
│ ok: [localhost]
│ 
│ TASK [Install docker.] *********************************************************
│ ok: [localhost]
│ 
│ TASK [Ensure docker is running] ************************************************
│ fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to start service docker: Job for docker.service failed because the control
│ process exited with error code.\nSee \"systemctl status docker.service\" and \"journalctl -xeu docker.service\" for details.\n"}
│ 
│ PLAY RECAP *********************************************************************
│ localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
│ 
│ 
╵
make: *** [apply] Error 1`

Also, I assume we can add a check so that the 3 variables are exclusive right?
